openapi: 3.1.0

info:
  version: 1.0.0
  title: Contact Management API
  description: >
    This API allows users to register, authenticate, and manage their contacts,
    including operations such as creating, updating, deleting, and retrieving individual records.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Contacts
    description: Operations for managing contact records

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-1-zsii.onrender.com

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
